Adding full MF1 capability (C++ and python)
njoy/ENDFtk pull request #107
Opened 2020-12-10 22:55 UTC by whaeck

This PR adds all missing MF1 components and sections in C++ and python

In addition, the following changes were made:
- the pybind11 dependency is changed from 2.6.0rc1 to 2.6.1 (latest regular release). We used the 2.6.0rc1 candidate before since it fixed an issue that we were having
- enumerated parsed files returned copies of sections using the section() or MT() method in the python bindings. This has been changed to a reference wrapper
- a few typos here and there
- parsing enumerated files directly from an ENDFtk.tree.File in python is now enabled

2020-12-11 16:58 UTC, nathangibson14 commented on python/src/ENDFtk.python.cpp
> +      "any_view< any_view< any_view< double, random_access >, random_access >, random_access >" );
Gotta love nested templates.  Random access!  Random access!! Random access!!!

2020-12-11 19:25 UTC, whaeck commented on python/src/ENDFtk.python.cpp
> +      "any_view< any_view< any_view< double, random_access >, random_access >, random_access >" );
Because it is ;-)

These things should not be created by the user but you still need to provide a name when wrapping. By providing the name this way, I'm making sure a user does not create one of these.

2020-12-17 20:51 UTC, nathangibson14 requested changes
I can't say I reviewed every line, but this looks really well done.  Hopefully the comments I left were helpful.

I'll approve once you consider my comments (although changes probably aren't really necessary) and I make sure it compiles and works in a few of my own Python examples.

2020-12-17 20:51 UTC, nathangibson14 commented on src/ENDFtk/section/1/455/DecayConstants/src/verifySize.hpp
> +    Log::info( "Expected NPL = 2 NNF with NNF > 0" );
This error message isn't quite consistent with the if statement.

2020-12-17 20:51 UTC, nathangibson14 commented on src/ENDFtk/section/1/456.hpp
> +   *  ENDFtk.MF1.File python bindings does not seem to handle it.
That's really unfortunate, ugh.

2020-12-17 20:51 UTC, nathangibson14 commented on src/ENDFtk/section/1/458/PolynomialComponents/src/generateList.hpp
> +    list.push_back( et[i][1] );
I don't think I see a better way, but this is ugly 😄

2020-12-17 20:51 UTC, nathangibson14 commented on src/ENDFtk/section/1/458/PolynomialComponents/test/PolynomialComponents.test.cpp
> +                                                     {{ -2.66e-1, 2.66e-2 }} };
Is this the interface you would expect someone creating a file to use?  So much syntax!  Do these things need objects with a user-friendly constructor?

2020-12-17 20:51 UTC, nathangibson14 commented on src/ENDFtk/section/1/458/TabulatedComponents/src/readTables.hpp
> +  while( NFC-- ) {
Can you trust NFC to be >= 0?

2020-12-17 20:51 UTC, nathangibson14 commented on src/ENDFtk/section/1/458/ThermalPointComponents/src/ctor.hpp
> +                        std::array< double, 2 >&& enp,
Is there an advantage to `std::array< double, 2 >` over `std::pair< double, double >`?

I wish there were cleaner way to handle all these.  I don't think the pair would be any better.

2020-12-17 20:51 UTC, nathangibson14 commented on src/ENDFtk/section/1/458/ThermalPointComponents/src/verify.hpp
> +  if ( NPL != 18 ) {
Why does ENDF have variables that aren't allowed to vary?

2020-12-17 20:51 UTC, nathangibson14 commented on src/ENDFtk/section/1/460/ContinuousPhotons/src/verifySize.hpp
> +  if ( NPL == 0 ) {
<= maybe?

2020-12-17 20:51 UTC, nathangibson14 commented on src/ENDFtk/section/1/460/DiscretePhotons/src/NC.hpp
> +  for ( auto& entry : this->photons_ ) { NC += entry.NC(); }
I don't like leaving this all on one line, personally.

2020-12-17 22:35 UTC, whaeck commented on python/src/section/1/451.python.cpp
> +    "MT451 - descriptive data and directory"
Everybody makes mistakes?

2020-12-17 22:36 UTC, whaeck commented on python/src/section/1/452.python.cpp
> +  using Multiplicity = njoy::ENDFtk::section::Type< 1, 452 >::Multiplicity;
Yeah, I should do that. I'll apply that in the fix/views branch since that branch combines all current pull requests.

2020-12-17 22:37 UTC, whaeck commented on python/src/section/1/452.python.cpp
> +    "    awr            the atomic weight ratio\n"
I think I fixed this already in the fix/views branch - I remember seeing that space yesterday

2020-12-17 22:38 UTC, whaeck commented on python/src/section/1/460.python.cpp
> +  )
Now I need to put a WH in there somewhere :-)

2020-12-17 22:39 UTC, whaeck commented on python/src/section/1/455/EnergyDependentConstants.python.cpp
> +    "    self            the component\n"
Even in my python code, I've always done this. What's the "official" rule on this?

2020-12-17 22:40 UTC, whaeck commented on python/src/tree/File.python.cpp
> +  using MF2 = njoy::ENDFtk::file::Type< 2 >;
Well, we could not parse MF2 directly on the tree.File, but tree.Section did allow for parsing the sections of MF2

2020-12-17 22:43 UTC, whaeck commented on python/test/Test_ENDFtk_MF1_MT460_DiscretePhotons.py
> +        # the data is copied
In rare cases, the standard "from_string" would need an additional argument (such as the number of discrete photons to be read in this case). Whenever that happens, I cannot use the standard component definitions which contains from_string. Due to the difference in signature, I left those out - hence me removing the test.

2020-12-17 22:44 UTC, whaeck commented on src/ENDFtk/file/1/test/1.test.cpp
> +        CHECK_THROWS( file.MT( 460_c ) );
They are valid but they are not present so the MT(...) function should throw an exception.

2020-12-17 22:45 UTC, whaeck commented on src/ENDFtk/file/1/test/1.test.cpp
>      WHEN( "a file::Type< 1 > is constructed from a syntaxTree" ){
I'll take a look at that.

2020-12-17 22:47 UTC, whaeck commented on src/ENDFtk/section/1/452/src/ctor.hpp
> +               head.MT(), MAT );
True, but some people complain about magic numbers :-)
This way, the actual MT number is only defined once, in the constexpr function MT().

2020-12-17 22:48 UTC, whaeck commented on src/ENDFtk/section/1/452/src/print.hpp
> +              this->nubar() );
Of course :-) All hail variant that makes the python code work nicely!

2020-12-17 22:51 UTC, whaeck commented on src/ENDFtk/section/1/455/DecayConstants/src/verifySize.hpp
> +    Log::info( "Expected NPL = 2 NNF with NNF > 0" );
In this case, NPL = 2NNF so that NPL cannot be zero (since NNF cannot be zero) and NPL cannot be odd.

2020-12-17 22:51 UTC, whaeck commented on src/ENDFtk/section/1/456.hpp
> +   *  ENDFtk.MF1.File python bindings does not seem to handle it.
I know, makes me sad

2020-12-17 22:51 UTC, whaeck commented on src/ENDFtk/section/1/458/PolynomialComponents/src/generateList.hpp
> +    list.push_back( et[i][1] );
I was too lazy to use ranges magic

2020-12-17 22:55 UTC, whaeck commented on src/ENDFtk/section/1/458/PolynomialComponents/test/PolynomialComponents.test.cpp
> +                                                     {{ -2.66e-1, 2.66e-2 }} };
That's a good point actually. I did this for consistency since MF8 MT457 also uses this construct to specify a value with it's uncertainty. In python, this simply translates to a list of two elements (the use of std::array imposes the length).

2020-12-17 22:57 UTC, whaeck commented on src/ENDFtk/section/1/458/TabulatedComponents/src/readTables.hpp
> +  while( NFC-- ) {
I hope so :-)
I probably should test NFC to be larger than or equal to 0 - to avoid an infinite loop.

2020-12-17 22:58 UTC, whaeck commented on src/ENDFtk/section/1/458/ThermalPointComponents/src/verify.hpp
> +  if ( NPL != 18 ) {
The energy release data consists of exactly 18 values.

2020-12-18 23:00 UTC, nathangibson14 approved these changes

2020-12-20 19:43 UTC, whaeck commented on src/ENDFtk/file/1/test/1.test.cpp
>      WHEN( "a file::Type< 1 > is constructed from a syntaxTree" ){
The file is unused so I removed it.

2020-12-21 16:39 UTC, merged