Feature/mf8
njoy/ENDFtk pull request #123
Opened 2021-02-27 01:33 UTC by whaeck

Fission yield sections have been added to MF8

2021-05-26 17:03 UTC, nathangibson14 requested changes

2021-05-26 17:03 UTC, nathangibson14 commented on src/ENDFtk/section/8/FissionYieldData/src/generateList.hpp
> +    Log::info( "The number of fission profucts and the fission product data "
`Log::error`?

2021-05-26 19:02 UTC, whaeck commented on src/ENDFtk/file/8.hpp
> +      RANGES_DECLTYPE_AUTO_RETURN( hana::make_tuple() )
We probably can get rid of it, but I'd like to leave it here for now until we get to implementing the non-enumerated sections for MF8.

2021-05-26 19:44 UTC, whaeck commented on src/ENDFtk/section/8/454/src/generateFissionYields.hpp
> +  while ( i++ < size ) {
I have no idea why I did it this way. I wrote this months ago ;-)

2021-05-26 19:44 UTC, whaeck commented on src/ENDFtk/section/8/459/src/generateFissionYields.hpp
> +static std::vector< FissionYieldData >
I removed this.

2021-05-26 19:44 UTC, whaeck commented on src/ENDFtk/section/8/459/src/NC.hpp
> + *  @brief Return the number of lines in this MF7/MT2 section
I removed this.

2021-05-27 20:40 UTC, nathangibson14 commented on src/ENDFtk/section/8/459.hpp
> +    // these deliberately reference MF8/MT454 since the code is common
Good comments to add! :)

2021-05-27 20:40 UTC, nathangibson14 approved these changes

2021-05-27 20:43 UTC, merged