Feature/mf14
njoy/ENDFtk pull request #124
Opened 2021-03-22 20:15 UTC by whaeck

Full MF14 support.

2021-06-23 16:23 UTC, nathangibson14 commented on src/ENDFtk/section/14/src/readPhotons.hpp
> +    NK -= NI;
Especially where you put this line requires a comment.  I was confused for a second, but I agree this is correct.

2021-06-23 16:55 UTC, nathangibson14 requested changes
Left a few comments that should be addressed.

Bigger picture, we may need to think of an easier interface for creating an `LI != 0` section.  Making a `IsotropicDiscreteDistribution` for each isotropic photon seems like overkill.  Maybe something where just a list of isotropic energies is given?

2021-06-23 16:55 UTC, nathangibson14 commented on src/ENDFtk/section/14.hpp
> +    int NK() const { return this->photons_.size(); }
For `LI=0`, `NK` need not be zero (and in fact technically shouldn't be), but `photons` will be an empty list.  This is a failing of the ENDF format, as `NK` is redundant information in that case.  But alas...

2021-06-23 16:55 UTC, nathangibson14 commented on src/ENDFtk/section/14.hpp
> +    bool isotropicAngularDistributions() const { return this->LI(); }
I don't like this variable name.  It sounds like it'll return a list of the isotropic distributions, when really it's just a flag.  ENDF doesn't give a name we need to follow.  Maybe `isotropicFlag` or `distributionsIsotropic`?  Pedantic, but might reduce confusion.

2021-06-23 16:55 UTC, nathangibson14 commented on src/ENDFtk/section/14.hpp
> +    }
This works, but ehhh.  This seems like something I'd just store and verify rather than computing.  But if it works, there's no real reason to change it.

2021-06-23 16:55 UTC, nathangibson14 commented on src/ENDFtk/section/14.hpp
> +    const auto& photonAngularDistributions() const { return this->photons_; }
This name is so similar to `isotropicAngularDistributions` with a totally different meaning, +1 for my previous comment.

2021-06-23 16:55 UTC, nathangibson14 commented on src/ENDFtk/section/14/TabulatedDistribution.hpp
> +  auto MU() const { return TabulationRecord::x(); }
You're doing the right thing, but `MU` as a variable name seems so wrong.  Silly ENDF-speak.

2021-06-23 16:55 UTC, nathangibson14 commented on src/ENDFtk/section/14/LegendreDistributions.hpp
> +  static constexpr int LTT() { return 1; }
I don't like defining `LI` and `LTT` for a single distribution, it's defined on the section level.  These quantities aren't defined at this level in ENDF, there are just 0s where you could imagine them being.

2021-06-23 16:55 UTC, nathangibson14 commented on src/ENDFtk/section/14/TabulatedDistributions.hpp
> +  static constexpr int LTT() { return 2; }
Same comment as with LegendreDistributions.  I don't think this belongs here.

2021-06-23 16:55 UTC, nathangibson14 commented on src/ENDFtk/section/14/TabulatedDistributions.hpp
> +class TabulatedDistributions :
I don't think this should be pluralized.  It's a TAB2 that you are representing, which I'd argue is just one `TabulatedDistribution`.  Likewise for Legendre.

2021-06-23 16:55 UTC, nathangibson14 commented on src/ENDFtk/section/4/Isotropic.hpp
> +  bool isotropicAngularDistributions() const { return this->LI(); }
Don't like this variable name here either :smile:

2021-06-23 16:55 UTC, nathangibson14 commented on python/src/section/14/TabulatedDistribution.python.cpp
> +    "    incident         the incident energy value\n"
Inconsistent variable name and argument.

2021-06-25 15:54 UTC, whaeck commented on src/ENDFtk/section/14.hpp
> +    bool isotropicAngularDistributions() const { return this->LI(); }
Well, technically it's a function name, not a variable :-)

What about isotropicDistributionFlag, since angular is understood by the isotropic in there.

2021-06-25 15:57 UTC, whaeck commented on src/ENDFtk/section/14.hpp
> +    bool isotropicAngularDistributions() const { return this->LI(); }
Maybe better isotropicDistributions() so that we can write:
```
if not data.isotropic_distributions :
    # do stuff
else :
    probability = 0.5
```

2021-06-25 22:40 UTC, nathangibson14 commented on src/ENDFtk/section/14.hpp
> +    bool isotropicAngularDistributions() const { return this->LI(); }
I can deal with `isotropicDistributions`, as it's at least significantly different from `photonAngularDistributions`.  But I think I like the option with `Flag` better.

2021-06-28 16:52 UTC, whaeck commented on src/ENDFtk/section/14/LegendreDistributions.hpp
> +  static constexpr int LTT() { return 1; }
This is similar to how some of the other sections work. The resonance formalism LRF value for instance is normally stored in the resonance region but we only store what is relevant and have each formalism component returns its LRF value when we need to using a static constexpr function (or a normal function when there's multiple possibilities). The MF6 sections use similar constructs with LAW/LANG.

2021-06-28 17:02 UTC, whaeck commented on python/src/section/14/TabulatedDistribution.python.cpp
> +    "    incident         the incident energy value\n"
Good catch.

2021-06-28 17:39 UTC, whaeck commented on src/ENDFtk/section/14/TabulatedDistributions.hpp
> +class TabulatedDistributions :
There already is a TabulatedDistribution - which is a single tabulate distribution for a specific energy (which is also used as the underlying distribution type in the TAB2).

As with some of the other remarks: similar names are used in MF6 as well. If we change this here, we'll have to change it everywhere. Keeping a consistently name interface is hard if you don't develop all of it at the same time.

2021-06-29 22:19 UTC, nathangibson14 approved these changes
Looks good now!

2021-06-29 23:52 UTC, merged