Feature/mf27
njoy/ENDFtk pull request #139
Opened 2021-07-15 18:13 UTC by whaeck

MF27 is now added. Like MF23 it is quite simple and almost identical to MF3.

This builds on #138 so that one needs to be merged first.

2021-07-27 22:07 UTC, nathangibson14 requested changes
Because MF27 data can mean different things, I'm a little iffy on the interface.  I think I'm okay with `energies` being something that can be returned, but I'd definitely change the constructor to be the more general `x`.

That all assumes that x isn't necessarily an energy.  The equations in the ENDF manual don't really make sense, as x appears without definition, and I don't know the physics enough to intuit it.  Do you know any more?

2021-07-27 22:07 UTC, nathangibson14 commented on src/ENDFtk/section/27.hpp
> +    auto values() const { return this->table.y(); }
Should you include the ENDF-speak of `H` for this?

2021-07-29 01:43 UTC, whaeck commented on src/ENDFtk/section/27.hpp
> +    auto energies() const { return this->table.x(); }
I've replaced this with X and H, no human readable version.

2021-08-02 14:14 UTC, nathangibson14 requested changes
One last fix needed, I'll just do it myself then approve.

2021-08-02 14:14 UTC, nathangibson14 commented on src/ENDFtk.hpp
> +#include "ENDFtk/section/27.hpp"
I don't know if this is my fault or yours, but this is missing 33.hpp

2021-08-02 14:14 UTC, nathangibson14 commented on src/ENDFtk.hpp
> +#include "ENDFtk/file/27.hpp"
Also missing 33.

2021-08-02 14:16 UTC, nathangibson14 approved these changes

2021-08-02 16:10 UTC, merged