Feature/mf33
njoy/ENDFtk pull request #141
Opened 2021-07-23 20:17 UTC by nathangibson14

Built off current develop, should be fun when we get all the 20s into develop, too.  A few clashes expected 😢 

Complete implementation of MF33 in both C++ and Python.

2021-07-23 20:18 UTC, whaeck commented
Alea iacta est ...

2021-07-26 23:12 UTC, whaeck requested changes
Nicely done. Some of the interface function names are debatable (looking at NC and NI) - as we've discussed previously - but we can change these at a later stage.

Basically, the remarks are for consistency in documentation and testing:
- add to_string tests on the python side
- use keyword arguments on the python side
- documentation on the C++ side

2021-07-26 23:12 UTC, whaeck commented on src/ENDFtk/section/33/DerivedRatioToStandard/src/ctor.hpp
> + *  Needs to be public for reading from Subsection.
I'll have to look more closely at this.

2021-07-26 23:12 UTC, whaeck commented on src/ENDFtk/section/33/Subsection/src/readNC.hpp
> +    ControlRecord cont( begin, end, lineNumber, MAT, MF, MT );
The only thing you need off here is the L2 value right?

Use that as an argument to the read constructor instead of moving an essentially useless CONT record into the components.

2021-07-26 23:12 UTC, whaeck commented on src/ENDFtk/section/33/Subsection/src/readNI.hpp
> +    ListRecord list( begin, end, lineNumber, MAT, MF, MT );
Here you're warranted to move the ListRecord into the components, because they are the components. With the CONT record in the NC subsections, it's not the same.

2021-07-27 16:09 UTC, nathangibson14 commented
I just renamed Subsection to ReactionBlock, NIType to ExplicitCovariance, and NCType to DerivedCovariance.  Any complaints with those?

--
Nathan A. Gibson
Staff Scientist, XCP-5 Nuclear Data Team
Los Alamos National Laboratory
(505) 665-2338

From: Wim Haeck ***@***.***>
Reply-To: njoy/ENDFtk ***@***.***>
Date: Monday, July 26, 2021 at 5:12 PM
To: njoy/ENDFtk ***@***.***>
Cc: "Gibson, Nathan Andrew" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [njoy/ENDFtk] Feature/mf33 (#141)


@whaeck requested changes on this pull request.

Nicely done. Some of the interface function names are debatable (looking at NC and NI) - as we've discussed previously - but we can change these at a later stage.

Basically, the remarks are for consistency in documentation and testing:

  *   add to_string tests on the python side
  *   use keyword arguments on the python side
  *   documentation on the C++ side

________________________________

In python/src/file/33.python.cpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r675845575>:

> +

+// declarations - sections

+void wrapSection_33( python::module&, python::module& );

+

+void wrapFile_33( python::module& module, python::module& viewmodule ) {

+

+  // type aliases

+  using Section = njoy::ENDFtk::section::Type< 33 >;

+  using File = njoy::ENDFtk::file::Type< 33 >;

+  using SectionRange = BidirectionalAnyView< Section >;

+

+  // create the submodule

+  python::module submodule = module.def_submodule(

+

+    "MF33",

+    "MF33 - covariances of neutron cross sections"

You should drop the neutron since these could also be for incident charged particles - I wager.

________________________________

In python/test/Test_ENDFtk_MF33_CovariancePairs.py<https://github.com/njoy/ENDFtk/pull/141#discussion_r675850152>:

> +            self.assertEqual( 4, chunk.number_values )

+            self.assertEqual( 2, chunk.NP )

+            self.assertEqual( 2, chunk.number_pairs )

+

+            # values

+            self.assertAlmostEqual( 1., chunk.Ek[0] )

+            self.assertAlmostEqual( 2., chunk.Fk[0] )

+            self.assertAlmostEqual( 3., chunk.Ek[1] )

+            self.assertAlmostEqual( 4., chunk.Fk[1] )

+            self.assertAlmostEqual( 1., chunk.first_array_energies[0] )

+            self.assertAlmostEqual( 2., chunk.first_array_fvalues[0] )

+            self.assertAlmostEqual( 3., chunk.first_array_energies[1] )

+            self.assertAlmostEqual( 4., chunk.first_array_fvalues[1] )

+

+            self.assertEqual( 2, chunk.NC )

+

to_string should go here

________________________________

In src/ENDFtk/section/33/Subsection/src/readNI.hpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r676062690>:

> +        Log::info( "MT value: {}", MT );

+        Log::info( "Line number: {}", lineNumber - 1 );

+        Log::info( "LB value: {}", list.L2() );

Some nitpicking: output the LB value after the list of legal LB values. The MT line is not required.

________________________________

In src/ENDFtk/section/33/Subsection/src/readNC.hpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r676062735>:

> +        Log::info( "MT value: {}", MT );

+        Log::info( "Line number: {}", lineNumber - 1 );

+        Log::info( "LTY value: {}", cont.L2() );

Some nitpicking: output the LTY value after the list of legal LTY values. The MT line is not required.

________________________________

In src/ENDFtk/section/33/Subsection/src/ctor.hpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r676062967>:

> +Subsection( Iterator& begin,

+      const Iterator& end,

+      long& lineNumber,

+      int MAT, int MF, int MT )

+try :

+  Subsection(

+    ControlRecord( begin, end, lineNumber, MAT, MF, MT ),

+    begin, end, lineNumber, MAT, MF, MT ) {

nitpicking: alignment of code

________________________________

In src/ENDFtk/section/33/Subsection/src/ctor.hpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r676063216>:

> +  Log::info( "Trouble while reading section {} of File 33 of Material {}",

+             MT, MAT );

This is a Subsection, so the message is inappropriate (and it would be added twice once the try ... catch in the actual MF33 section is encountered). A better message would be:

    Log::info( "Encountered error while constructing a covariance subsection" );

________________________________

In src/ENDFtk/section/33/Subsection/src/ctor.hpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r676063255>:

> + *  NI Only.

+ *

+ */

Argument documentation is missing.

________________________________

In src/ENDFtk/section/33/Subsection/src/ctor.hpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r676063348>:

> + *  NC Only.

+ *

+ */

Argument documentation is missing

________________________________

In src/ENDFtk/section/33/Subsection/src/NC.hpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r676063471>:

> @@ -0,0 +1,21 @@

+long NC() const {

nitpicking: documentation is missing

________________________________

In src/ENDFtk/section/33/Subsection.hpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r676063943>:

> +  double xmf1_;

+  double xlfs1_;

You should make these integers, or even unsigned integers. It's not because the ENDF format says that it is stored as a double that you need to interpret it as a double. Conversion to double is done when writing out the file.

________________________________

In src/ENDFtk/section/33/Subsection.hpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r676064119>:

> +  double XMF1() const { return this->xmf1_; }

+

+  /**

+   *  @brief Return the file number for the second cross section

+   */

+  double secondFileNumber() const { return this->XMF1(); }

+

+  /**

+   *  @brief Return the final excited state for the second cross section

+   */

+  double XLFS1() const { return this->xlfs1_; }

+

+  /**

+   *  @brief Return the final excited state for the second cross section

+   */

+  double secondFinalExcitedState() const { return this->XLFS1(); }

+

+  /**

+   *  @brief Return the material number for the second cross section

+   */

+  double MAT1() const { return this->mat1_; }

+

+  /**

+   *  @brief Return the material number for the second cross section

+   */

+  double secondMaterialNumber() const { return this->MAT1(); }

+

+  /**

+   *  @brief Return the section number for the second cross section

+   */

+  double MT1() const { return this->mt1_; }

+

+  /**

+   *  @brief Return the section number for the second cross section

+   */

+  double secondSectionNumber() const { return this->MT1(); }

These return types should be integers. You're actually converting the mat1_ and mt1_ to doubles from integers. I assume this is a copy/paste error.

________________________________

In src/ENDFtk/section/33/Subsection.hpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r676064339>:

> +   *  @brief Return the section number for the second cross section

+   */

+  double secondSectionNumber() const { return this->MT1(); }

+

+  /**

+   *  @brief Return the number of NC-type subsubsections

+   */

+  int NK() const { return this->nc_.size(); }

+

+  /**

+   *  @brief Return the number of NC-type subsubsections

+   */

+  int numberNCType() const { return this->NK(); }

+

+  /**

+   *  @brief Return the number of NC-type subsubsections

This is for NI, not NC

________________________________

In src/ENDFtk/section/33/Subsection.hpp<https://github.com/njoy/ENDFtk/pull/141#discussion_r676064362>:

> +

+  /**

+   *  @brief Return the number of NI-type subsubsections

+   */

+  int numberNIType() const { return this->NI(); }

+

+  /**

+   *  @brief Return the NC-type subsubsections

+   */

+  auto componentsNC() const {

+

+    return ranges::cpp20::views::all( this->nc_ );

+  }

+

+  /**

+   *  @brief Return the NC-type subsubsections

this is for NI, not NC

________________________________

In src/ENDFtk/section/33/DerivedRedundant/src/NC.h [...]

2021-07-27 21:29 UTC, nathangibson14 commented
This should be ready to go.  I address at least most of the comments, and then found a few of my own issues (e.g., missing a constructor for `CovariancePairs` on the Python side.  Looks like the CI passes again.

2021-07-29 01:53 UTC, whaeck requested changes
Just a few more trivial items. The double return type is the most important one - you did not see this in the tests since the numbers you used can be represented using integers.

2021-07-29 01:53 UTC, whaeck commented on src/ENDFtk/section/33/DerivedRatioToStandard.hpp
> +  int upperEnergy() const { return this->E2(); }
The return types on these should probably be doubles

2021-07-29 01:53 UTC, whaeck commented on src/ENDFtk/section/33/ReactionBlock/src/NC.hpp
> +long NC() const {
Missing documentation

2021-07-29 13:48 UTC, whaeck approved these changes
And we're off to the races ...

2021-07-29 17:49 UTC, merged